tap "FelixKratz/formulae"
tap "mediosz/tap"
tap "nikitabobko/tap"
tap "koekeishiya/formulae"

brew "stow"
brew "starship"
brew "borders"
brew "zellij"
brew "koekeishiya/formulae/yabai"
brew "koekeishiya/formulae/skhd"

cask "ghostty"
cask "kitty"
cask "aerospace"
cask "font-jetbrains-mono-nerd-font"
